#!/bin/bash
user="db user";
pass="db pass";
db="database";
table="db table";
Gid="$1";
paths="Folder path for files to compare with the database";

DB_COUNT=$(mysql -u${user} -p${pass} -D ${db} -se "SELECT COUNT(*) FROM ${table} where GroupID='${Gid}';")
FILE_COUNT=$(ls -1 ${paths}/${Gid}/*.call | wc -l)

echo "📊 資料庫筆數：$DB_COUNT"
echo "📄 TXT 檔案數量：$FILE_COUNT"

if [ "$DB_COUNT" -eq "$FILE_COUNT" ]; then
    echo "✅ 數量相符，進行檔名檢查..."
    
    DB_NUMBERS=$(mysql -u${user} -p${pass} -D ${db} -se "SELECT mobile1 FROM member WHERE GroupID = '${Gid}';")
    ALL_MATCHED=true

    for num in $DB_NUMBERS; do
        if [ -f "${paths}/${Gid}/${Gid}_${num}.call" ]; then
            continue;
        else
            echo "❌ ${Gid}__${num}.call 缺失！"
            ALL_MATCHED=false
        fi
    done

    if [ "$ALL_MATCHED" = true ]; then
        echo "✅ 所有檔案名稱與資料庫記錄相符！"
    else
        echo "❌ 存在遺漏或命名錯誤的檔案，請檢查！"
    fi
else
    echo "❌ 數量不符，請檢查檔案產生過程！"
fi
